### --- Status Bar ---
set -g status-interval 1
set -g status-justify centre
set -g status-bg colour234
set -g status-fg white

set -g status-left-length 40
set -g status-right-length 120

set -g status-left "#[fg=green]#S #[fg=cyan]| #[fg=yellow]#(whoami)"
set -g status-right "#[fg=cyan]%Y-%m-%d #[fg=green]%H:%M #[fg=yellow]#(uptime | awk '{print $3,$4,$5}')"

### --- Window Titles ---
setw -g automatic-rename on
set -g set-titles on
set -g set-titles-string "#W"
